# Generated by Django 4.2.1 on 2023-10-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_updates"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teachers",
            fields=[
                ("teacher_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=10)),
                ("image", models.ImageField(upload_to="teacher_photos")),
                ("url", models.CharField(max_length=100)),
                ("add_date", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
