# Generated by Django 4.2.1 on 2023-10-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_teachers"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachers",
            name="role",
            field=models.CharField(default="assistant teacher", max_length=10),
        ),
    ]
