# Generated by Django 4.2.1 on 2023-10-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_alter_teachers_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Uploads",
            fields=[
                ("upload_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=25)),
                ("standard", models.CharField(max_length=25)),
                ("roll_no", models.CharField(max_length=25)),
                ("subject", models.CharField(max_length=25)),
                ("image", models.ImageField(upload_to="student_uploads")),
                ("url", models.CharField(max_length=100)),
                ("add_date", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
