# Generated by Django 4.2.1 on 2023-10-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_uploads"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploads",
            name="image",
            field=models.FileField(upload_to=""),
        ),
    ]
