# Generated by Django 4.2.1 on 2023-10-01 17:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_alter_uploads_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploads",
            name="url",
        ),
    ]
